on: [push]
name: build
jobs:
  runhaskell:
    name: cabal test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: haskell-actions/setup
      - uses: actions/cache
        name: Caching
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}
      - run: cabal test
